In [1]:
import numpy as np

In [2]:
#Creating numpy array using list
my_list=[1,2,3]
my_array=np.array(my_list)
print(my_array)

[1 2 3]


In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#Creating numpy array using builtin functions
print(np.arange(1,99,3))  #start,stop,step
#Stop value is not getting included

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


  ##### Creates an array with equally spaced 50 values on numberline between 1 and 100,not to be confused with arange,the stop value is included in result unlike arange()

In [13]:
print(np.linspace(1,100,50)) 

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [11]:
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
print(np.ones((10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
# random number array
print("2 random numbers:")
print(np.random.rand(2))
print("\nRandom matrix of 5x5: ")
print(np.random.rand(5, 5))

2 random numbers:
[0.61710317 0.48978751]

Random matrix of 5x5: 
[[0.96882785 0.21242441 0.98417637 0.11092246 0.33832122]
 [0.38888522 0.00209576 0.07064222 0.68311386 0.66656925]
 [0.11298221 0.80554792 0.17926446 0.45038314 0.72453827]
 [0.45623925 0.33719707 0.9003582  0.94712911 0.65082387]
 [0.58120962 0.05749598 0.71311648 0.18692777 0.34595085]]


In [24]:
# Normal Distribution
print("2 random numbers from normal distribution:")
print(np.random.randn(2))
print("\nRandom matrix of 5x5 from normal distribution: ")
print(np.random.randn(5, 5))

2 random numbers from normal distribution:
[-0.43333912  0.06562524]

Random matrix of 5x5 from normal distribution: 
[[ 1.28660609 -0.4633896  -0.75477118 -0.33029173  0.20742197]
 [-0.66110327  1.63976003  0.33858592  2.04099127 -1.19691411]
 [ 1.54132468 -0.05870354 -1.37522969 -1.22895972 -0.33563471]
 [-1.87057389  0.1891801   0.28962584 -1.61037892  0.65280941]
 [ 0.00830372 -0.04870259  0.55203738  0.70415939  0.78615405]]


In [25]:
# Random integers from low(inclusive) to high(exclusive)

print("Single random integers between 1 and 100: ")
print(np.random.randint(1, 100))

print("\n10 random integers between 1 and 100: ")
print(np.random.randint(1, 100, 10))

Single random integers between 1 and 100: 
11

10 random integers between 1 and 100: 
[74 99 98 21 42 54 87 46 36 99]


In [27]:
# Seeding for reproducable results
seed = 77
print(f"Seeding number '{seed}' for reproducable results: ")

np.random.seed(seed)
print(np.random.rand(4)) # 4 random numbers # These for random values will be same on all machines in the world

Seeding number '77' for reproducable results: 
[0.91910903 0.6421956  0.75371223 0.13931457]


In [28]:
# Storing

arr = np.arange(25) # numbers from 0 to 4

# 10 random numbers between 0 and 50
random_arr = np.random.randint(0, 50, 10)

print(arr)
print(random_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[32 39 44 19 32 36 36 47 14 15]


In [29]:
# Reshape: Returns an array containing the same data
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
# Max, Min, and their index positions

print("Max element in array: ", random_arr.max())
print("Min element in array: ", random_arr.min())
print("Index of max element: ", random_arr.argmax())
print("Index of min element: ", random_arr.argmin())

Max element in array:  47
Min element in array:  14
Index of max element:  7
Index of min element:  8


In [36]:
# Bracket indexing and selection - similar to python list
# Get a value at an index
print(arr[8])

8


In [37]:
# Reset array, Why??
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
# Conditional selection
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
''' Check each element of the array against the condition
which returns a boolean array where
'''

In [ ]:
print(arr[arr>4])

### *Assignment*

In [40]:
# 1. Create an array of 10 zeros
zero_arr = np.zeros(10)
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [41]:
# 2. Create an array of 10 ones
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [42]:
# 3. Create an array of 10 fives
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [43]:
# 4. Create an array of the integers from 10 to 50
print(np.arange(10, 51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [44]:
# 5. Create an array of all the even integers from 10 to 50
print(np.arange(10, 51, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [51]:
# 6. Create a 3x3 matrix with values ranging from  0 to 8
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
