#### 1. Write a NumPy program to get the numpy version and show numpy build configuration

In [19]:
import numpy as np

print("Version: ", np.__version__)

print("\nConfiguration: ")
np.show_config()

Version:  1.20.3

Configuration: 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 2. Write a NumPy program to get help on add function

In [37]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [38]:
np.add?

#### 3. Write a NumPy program to test whether none of the elements of the given array is zero

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

if False in (arr!=0):
    print("Zero exists in array")
else:
    print("It is an non zero array")

It is an non zero array


#### 4. Write a NumPy program to test whether any of the given element of array is non-zero

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

if False in (arr!=0):
    print("Zero exists in array")
else:
    print("It is an non zero array")

It is an non zero array


#### 5. Write a NumPy program to test element-wise for finiteness

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, np.inf])

print(np.isfinite(arr))

[ True  True  True  True  True  True  True  True  True  True False]


In [81]:
# If any infinite value is present or not?
if np.inf in arr:
    print(True)
else:
    print(False)

True


In [80]:
# Create another array without infinite values
arr1 = arr[np.isfinite(arr)]
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 6. Write a NumPy program to test element-wise for positive or negative infinity

In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, np.inf, np.NINF, 10])

print(np.isfinite(arr))

[ True  True  True  True  True  True  True  True  True False False  True]


#### 7. Write a NumPy program to test element-wise for NaN in given array

In [107]:
arr = np.array([1, 2, np.nan, 4, 5, 6, 7, 8, 9, 10])
np.isnan(arr)

array([False, False,  True, False, False, False, False, False, False,
       False])

#### 8. Write a numpy program to test element wise for complex number, real number of a given array,also find out wheather a given number is a scalar type or not

In [166]:
arr = np.array([1, 2, 4, 5, 6, 7, 8, 9, 10])
np.isscalar([2])

False

#### 9. Write a numpy  program to create an element wise comparison of two given arrays.


In [123]:
arr = np.array([1, 2,4, 5, 6, 7, 8, 9, 10])
arr1=np.array([1,2,3,5,6,7,8,9,10])
arr>arr1

array([False, False,  True, False, False, False, False, False, False])

#### 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [142]:
arr=np.array([1,7,13,105])
arr.nbytes

16

#### 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [150]:
arr=np.zeros(10)
arr1=np.ones(10)
arr2=np.ones(10)*5
arr=np.append(arr,arr1)
arr=np.append(arr,arr2)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 12. Write a NumPy program to create an array of the integers from 30 to70.

In [152]:
arr=np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

#### 13. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [154]:
arr=np.arange(30,71)
arr=arr[arr%2==0]
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

#### 14. Write a NumPy program to create a 3x3 identity matrix.

In [155]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 15. Write a NumPy program to generate a random number between 0 and 1.

In [163]:
arr=np.random.rand()
arr

0.9644192592983857

#### 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [271]:
# Syntax: np.random.normal( mean, Standard_Deviation, size )
arr = np.random.normal(1, 1, 15)
arr

array([-0.23223481, -0.51939666,  0.4410579 ,  0.04294721,  0.5206351 ,
        1.03713814,  2.17556674,  1.10668249,  0.47592253,  1.12659685,
        0.28778182, -0.39369157,  2.29744598,  0.28093748,  0.38048861])

#### 17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [165]:
arr=np.arange(15,56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

#### 18. Write a NumPy program to create a 3X4 array.

In [168]:
arr=np.random.randint(1,100,(3,4))
arr

array([[39, 53, 94, 30],
       [85, 63, 19, 24],
       [ 8, 83,  8, 22]])

#### 19. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [169]:
arr=np.linspace(5,50,10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

#### 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [172]:
arr=np.arange(0,21)
arr[9:16]=-arr[9:16]
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

#### 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [173]:
arr=np.random.randint(0,10,5)
arr

array([0, 2, 9, 2, 2])

#### 22. Write a NumPy program to multiply the values of two given vectors.

In [174]:
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
print(arr*arr1)

[ 4 10 18]


#### 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [176]:
arr=np.random.randint(10,21,(3,4))
arr

array([[13, 11, 19, 11],
       [16, 20, 14, 10],
       [16, 12, 11, 16]])

#### 24. Write a NumPy program to find the number of rows and columns of a given matrix.

In [179]:
arr=np.random.randint(10,21,(3,4))
print("Rows :",arr.shape[0])
print("Coloumns :",arr.shape[1])

Rows : 3
Coloumns : 4


#### 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [180]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [185]:
arr=np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [194]:
arr[0]=1
arr[:,0]=1
arr[-1]=1
arr[:,-1]=1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [196]:
arr = np.array([1, 2, 3, 4, 5])

In [197]:
print(np.diag(arr))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [202]:
arr = np.random.randint(1, 28, (3, 3, 3))
arr

array([[[17,  2, 23],
        [25, 24,  5],
        [ 3,  1, 11]],

       [[ 5, 22,  5],
        [18, 20,  1],
        [13, 18, 19]],

       [[ 6, 15, 19],
        [ 2, 11, 19],
        [ 7,  5,  1]]])

#### 29. Write a NumPy program to compute the inner product of two given vectors.

In [206]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Dot product/Inner Product: ", v1.dot(v2))

Dot product/Inner Product:  32


#### 30. Write a NumPy program to sort a given array by row and column in ascending order.

In [215]:
arr = np.random.randint(1, 30, (3,5))
arr

array([[26,  4,  2, 12, 15],
       [26, 23, 24,  7, 12],
       [ 6, 24, 21,  5, 26]])

In [216]:
arr.sort(axis=0) # Row-wise sorted
arr

array([[ 6,  4,  2,  5, 12],
       [26, 23, 21,  7, 15],
       [26, 24, 24, 12, 26]])

In [217]:
arr.sort(axis=1) #Column-wise sorted
arr

array([[ 2,  4,  5,  6, 12],
       [ 7, 15, 21, 23, 26],
       [12, 24, 24, 26, 26]])

#### 31. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [243]:
arr = np.arange(0, 50)
num = 45
print("Numbers less than 45:", arr[arr<45])
print("\nNumbers greater than 45:", arr[arr>45])

Numbers less than 45: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]

Numbers greater than 45: [46 47 48 49]


#### 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.

In [262]:
arr = np.arange(0, 50)
num = 45
l = arr[arr<45]
l[:] = 0

e = arr[arr==45]
e[:] = 1

r = arr[arr>45]
r[:] = 2


print("Numbers less than 45 replaced by 0:", l)
print("\nNumbers equal to 45 replaced by 1:", e)
print("\nNumbers greater than 45 replaced by 2:", r)

Numbers less than 45 replaced by 0: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0]

Numbers equal to 45 replaced by 1: [1]

Numbers greater than 45 replaced by 2: [2 2 2 2]


#### 33. Write a NumPy program to create an array of equal shape and data type of a given array.

In [239]:
arr = np.random.randint(1, 10, (3,4))
arr1 = np.zeros_like(arr)
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [231]:
arr = np.random.randint(1, 30, (3,4,5))
arr

array([[[19, 28, 22, 13, 29],
        [10, 27, 19, 25, 22],
        [23,  1,  3, 14, 17],
        [12, 17,  6, 26, 29]],

       [[ 3,  9, 15,  3, 29],
        [16, 23,  5, 24, 17],
        [27,  6,  7, 13, 20],
        [ 7, 11, 11,  2,  3]],

       [[18, 18, 13, 12, 22],
        [28,  7, 21, 16, 28],
        [21,  9, 27,  1, 23],
        [20, 25, 16,  7,  9]]])

#### 35. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [233]:
a = np.array([1, 2, 3])
b = np.array([7, 8, 9])
print(a*b)

[ 7 16 27]
